version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: "src/consumer.py"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: "src/consumer.py"
    volumes:
      - .:/app
    depends_on:
      - rabbitmq